kind: pipeline
name: with-tailwind
type: docker

trigger:
  event:
    - pull_request
  branch:
    - main

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    settings:
      restore: true
      mount:
        - ./with-tailwind/frontend/node_modules
    volumes:
      - name: cache
        path: /cache

  - name: install
    image: node:16.9.1
    depends_on: [ restore-cache ]
    commands:
      - cd ./with-tailwind/frontend
      - yarn install

  - name: lint
    image: node:16.9.1
    depends_on: [install]
    commands:
      - cd ./with-tailwind/frontend
      - yarn lint

  - name: build
    image: node:16.9.1
    depends_on: [install]
    commands:
      - cd ./with-tailwind/frontend
      - yarn build

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    depends_on: [install]
    settings:
      rebuild: true
      mount:
        - ./with-tailwind/frontend/node_modules
    volumes:
      - name: cache
        path: /cache

volumes:
  - name: cache
    host:
      path: /tmp/drone/cache/${DRONE_REPO}/tailwind

---

kind: pipeline
name: with-tailwind-daisyui
type: docker

trigger:
  event:
    - pull_request
  branch:
    - main

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    settings:
      restore: true
      mount:
        - ./with-tailwind-daisyui/frontend/node_modules
    volumes:
      - name: cache
        path: /cache

  - name: install
    image: node:16.9.1
    depends_on: [ restore-cache ]
    commands:
      - cd ./with-tailwind-daisyui/frontend
      - yarn install

  - name: lint
    image: node:16.9.1
    depends_on: [install]
    commands:
      - cd ./with-tailwind-daisyui/frontend
      - yarn lint

  - name: build
    image: node:16.9.1
    depends_on: [install]
    commands:
      - cd ./with-tailwind-daisyui/frontend
      - yarn build

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    depends_on: [install]
    settings:
      rebuild: true
      mount:
        - ./with-tailwind-daisyui/frontend/node_modules
    volumes:
      - name: cache
        path: /cache

volumes:
  - name: cache
    host:
      path: /tmp/drone/cache/${DRONE_REPO}/tailwind-daisyui

---

kind: pipeline
name: with-tailwind-mantine
type: docker

trigger:
  event:
    - pull_request
  branch:
    - main

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    settings:
      restore: true
      mount:
        - ./with-tailwind-mantine/frontend/node_modules
    volumes:
      - name: cache
        path: /cache

  - name: install
    image: node:16.9.1
    depends_on: [ restore-cache ]
    commands:
      - cd ./with-tailwind-mantine/frontend
      - yarn install

  - name: lint
    image: node:16.9.1
    depends_on: [install]
    commands:
      - cd ./with-tailwind-mantine/frontend
      - yarn lint

  - name: build
    image: node:16.9.1
    depends_on: [install]
    commands:
      - cd ./with-tailwind-mantine/frontend
      - yarn build

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    depends_on: [install]
    settings:
      rebuild: true
      mount:
        - ./with-tailwind-mantine/frontend/node_modules
    volumes:
      - name: cache
        path: /cache

volumes:
  - name: cache
    host:
      path: /tmp/drone/cache/${DRONE_REPO}/tailwind-mantine
