kind: pipeline
name: lint-build-scaffolds
type: docker

trigger:
  event:
    - pull_request
  branch:
    - main

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    settings:
      restore: true
      mount:
        - ./minimal/frontend/node_modules
        - ./with-tailwind/frontend/node_modules
        - ./with-tailwind-daisyui/frontend/node_modules
        - ./with-tailwind-flowbite/frontend/node_modules
        - ./with-tailwind-daisyui/frontend/node_modules
    volumes:
      - name: cache
        path: /cache

  - name: install-minimal
    image: node:16.9.1
    depends_on: [ restore-cache ]
    commands:
      - cd ./minimal/frontend
      - yarn install

  - name: install-tailwind
    image: node:16.9.1
    depends_on: [ restore-cache ]
    commands:
      - cd ./with-tailwind/frontend
      - yarn install

  - name: install-tailwind-daisyui
    image: node:16.9.1
    depends_on: [ restore-cache ]
    commands:
      - cd ./with-tailwind-daisyui/frontend
      - yarn install

  - name: install-tailwind-flowbite
    image: node:16.9.1
    depends_on: [ restore-cache ]
    commands:
      - cd ./with-tailwind-flowbite/frontend
      - yarn install

  - name: install-tailwind-mantine
    image: node:16.9.1
    depends_on: [ restore-cache ]
    commands:
      - cd ./with-tailwind-mantine/frontend
      - yarn install

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    depends_on: [install-minimal, install-tailwind, install-tailwind-daisyui, install-tailwind-flowbite, install-tailwind-mantine]
    settings:
      rebuild: true
      mount:
        - ./minimal/frontend/node_modules
        - ./with-tailwind/frontend/node_modules
        - ./with-tailwind-daisyui/frontend/node_modules
        - ./with-tailwind-flowbite/frontend/node_modules
        - ./with-tailwind-daisyui/frontend/node_modules
    volumes:
      - name: cache
        path: /cache

volumes:
  - name: cache
    host:
      path: /tmp/drone/cache/${DRONE_REPO}
