kind: pipeline
name: default
type: docker

trigger:
  event:
    - pull_request
  branch:
    - main

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    settings:
      restore: true
      mount:
        - ./with-tailwind/frontend/node_modules
    volumes:
      - name: cache
        path: /cache

  - name: install
    image: node:16.9.1
    depends_on: [ restore-cache ]
    commands:
      - cd with-tailwind/frontend
      - yarn install

  - name: lint
    image: node:16.9.1
    depends_on: [install]
    commands:
      - cd with-tailwind/frontend
      - yarn lint

  - name: typescript-check
    image: node:16.9.1
    depends_on: [install]
    commands:
      - cd with-tailwind/frontend
      - yarn type-check

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    depends_on: [install]
    settings:
      rebuild: true
      mount:
        - ./with-tailwind/frontend/node_modules
    volumes:
      - name: cache
        path: /cache

volumes:
  - name: cache
    host:
      path: /tmp/drone/cache/${DRONE_REPO}
