name: Frontend Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: frontend_lint_build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "yarn"
          cache-dependency-path: frontend/yarn.lock

      - name: Install dependencies
        run: |
          cd ./frontend
          yarn install --frozen-lockfile

      - name: Lint code
        run: |
          cd ./frontend
          yarn lint

      - name: Build Project
        run: |
          cd ./frontend
          yarn build
